name: flutter_demo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:

  flutter:
     sdk: flutter

  flutter_localizations:
    sdk: flutter

  carousel_slider: ^4.0.0
  smooth_page_indicator : ^1.1.0
  auto_route: ^8.1.3
  cupertino_icons: ^1.0.6

  #networking
  retrofit: ^4.0.3
  dio: ^5.3.3

  #service locater
  get_it: ^7.6.4

  #core
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  flutter_hooks: ^0.20.3

  #ui
  shimmer: ^3.0.0
  flutter_svg: ^2.0.7
  ionicons: ^0.2.2

  # state management
  flutter_bloc: ^8.1.3

  #comparing dart objects
  equatable: ^2.0.5

  #Database
  floor: ^1.4.2
  flutter_staggered_grid_view: ^0.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^8.0.0
  floor_generator: ^1.4.2
  retrofit_generator: ^8.0.4
  build_runner: ^2.4.6
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  generate : true

flutter_intl:
    enabled: true